name: tagged-release
# Execute this action only when pushing a tag
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    # Necessary permission to make a release
    permissions:
      contents: write
    steps:
      # Get access to the repo
      - uses: actions/checkout@v3
      # Get node
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Install dependencies
      - run: npm install
      # Create package
      - run: ./build-zip
      # Auto release
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "${{ github.event.repository.name }}.zip"